Repository nhsx/AIF_Allocation_Tool, pull requests merged in 2021-12, with the labels that each got.

#22 Refactor new deploy mf
  app/dashboard.py
Labels: enhancement

#27 Mf dev branch
  .DS_Store
  dashboard.py
  requirements.txt
  utils.py
Labels: bug

#30 NHSX Version 0.01
  .streamlit/config.toml
  README.md
  SessionState.py
  __pycache__/SessionState.cpython-39.pyc
  allocation_tool.py
  dashboard.py
  data/GP Practice WP_2022_23_run9.xlsx
  data/wp_data.csv
  data/wp_data_2022LAD.csv
  docs/ICB allocation tool documentation.txt
  docs/json_format_primer.md
  docs/screenshot-min.png
  images/nhs_logo.png
  requirements.txt
  utils.py
Labels: bug, documentation, enhancement
